# Generated by Django 3.1.4 on 2020-12-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.ImageField(default=True, upload_to='F:\\DJANGO_FILES\\djclass\\media'),
            preserve_default=False,
        ),
    ]
