# Generated by Django 3.1.4 on 2020-12-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makefrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='MEDIA_ROOT'),
        ),
    ]
